using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class zbieranieItem贸w : MonoBehaviour
{
    private licznikitem贸w licznikI;
    // Start is called before the first frame update
    void Start()
    {
        licznikI = GameObject.Find("Manager").GetComponent<licznikitem贸w>();
        if (licznikI == null)
        {
            Debug.LogError("LicznikItem贸w nie znaleziony");
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }

     void OnTriggerEnter2D(Collider2D col)
    {
        Debug.Log("GameObject1 collided with " + col.name);
        if (col.gameObject.name == "Idle (1)")
        {
            this.gameObject.SetActive(false);
            licznikI.zebranoItem();
        }
            
    }
}
